# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160209_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.Resource'),
        ),
        migrations.AlterField(
            model_name='task',
            name='days_worked',
            field=models.IntegerField(default=0),
        ),
    ]
