# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 20:51
from __future__ import unicode_literals

import random
import string

from django.db import migrations, models

def set_permalinks(apps, schema_editor):
    model = apps.get_model('schedule', 'Project')
    for row in model.objects.all():
        row.permalink = ''.join(random.choice(string.ascii_lowercase
                                              + string.ascii_uppercase
                                              + string.digits)
                                for i in range(10))
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20160224_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='permalink',
            field=models.CharField(max_length=10, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(set_permalinks,
                             reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='permalink',
            field=models.CharField(max_length=10, default='', unique=True)
        ),
    ]
