# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20160302_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('used', models.DecimalField(decimal_places=1, max_digits=2, validators=[schedule.models.validate_half_day_granularity])),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Resource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Task')),
            ],
        ),
    ]
